import { Geist, Geist_Mono, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dopex",
  description: "Generated by team Dopex",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Load the GA script asynchronously */}
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-TMHKP9874R"
        ></script>
        <script
          type="text/javascript"
          src="https://map.acumatica.com/track/0q9epsuy8e87/payload.js"
          async
        ></script>

        {/* Inline configuration script using dangerouslySetInnerHTML */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-TMHKP9874R');
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster position="top-center" />
        {children}
      </body>
    </html>
  );
}
